-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 16:30:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema usuarios2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `usuarios2` ;

-- -----------------------------------------------------
-- Schema usuarios2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuarios2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `usuarios2` ;


-- -----------------------------------------------------
-- Table `usuarios2`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios2`.`administrador` (
   `nombre` VARCHAR(45) not NULL,
   `id` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));

insert into administrador(nombre, id,clave) values ('Juan Perez','111','111UNA');
insert into administrador( nombre, id,clave) values ('Carolina Hernandez','222','222UNA');



 
 

-- `image` LONGBLOB,
-- -----------------------------------------------------
-- Table `usuarios2`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios2`.`medico` (
  `nombre` VARCHAR(45) NOT NULL,
  `idMedicos` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `tarifa` INT,
  `nombre_provincia`VARCHAR(45) ,
  `nombre_especialidad` VARCHAR(45) ,
  `horario` int NULL,
  PRIMARY KEY (`idMedicos`),
	CONSTRAINT `horario_ibfk_2`
    FOREIGN KEY (`horario`)
    REFERENCES `usuarios2`.`slot` (`id`));



insert into medico(nombre,idMedicos,clave,tarifa,nombre_provincia,nombre_especialidad) values
('Martín Elías Acosta','1111','11111',10000,'San Jose','Cardiologia');

insert into medico(nombre,idMedicos,clave,tarifa,nombre_provincia,nombre_especialidad) values
('Ana María de la Peña','2222','22222',15000,'San Jose','Ginegologia');






-- -----------------------------------------------------
-- Table `usuarios2`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios2`.`paciente` (
  `nombre` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
`enfermedades` VARCHAR(45) NULL,
  `alergias` VARCHAR(45)  NULL,
  `cirugias` VARCHAR(45) NULL,
`contacto_emergencia` VARCHAR(45)  NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

insert into paciente(nombre,cedula,enfermedades,alergias,cirugias,contacto_emergencia) values ('Maria','111','Si tiene','No tiene','Si tiene','888888');
insert into paciente(nombre,cedula,enfermedades,alergias,cirugias,contacto_emergencia) values ('Henry','222',null,null,null,null);
insert into paciente(nombre,cedula,enfermedades,alergias,cirugias,contacto_emergencia) values ('Daniel','333',null,null,null,null);






-- -----------------------------------------------------
-- Table `usuarios2`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios2`.`cita` (
  `idCitas` INT auto_increment NOT NULL,
  `estado` VARCHAR(20)  NULL,
  `dia` VARCHAR(20),
  `hora` VARCHAR(20),
  `signos`  VARCHAR(45) NULL,
  `diagnostico` VARCHAR(45)  NULL,
  `medicinas` VARCHAR(45) NULL,
  `Paciente_cedula` VARCHAR(45) NOT NULL,
  `Medico_idMedico` VARCHAR(45)  NOT NULL,
  PRIMARY KEY (`idCitas`),
  CONSTRAINT `cita_ibfk_1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `usuarios2`.`medico` (`idMedicos`),
  CONSTRAINT `cita_ibfk_2`
    FOREIGN KEY (`Paciente_cedula`)
    REFERENCES `usuarios2`.`paciente` (`cedula`));

CREATE INDEX `Medico_idMedico` ON `usuarios2`.`cita` (`Medico_idMedico` ASC) VISIBLE;

CREATE INDEX `Paciente_cedula` ON `usuarios2`.`cita` (`Paciente_cedula` ASC) VISIBLE;



-- -----------------------------------------------------
-- Table `usuarios2`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios2`.`horario` (
  `numero` INT auto_increment NOT NULL,
  `id_doctor` VARCHAR(45) NOT NULL,
   comienzo_lunes int,
   finaliza_lunes int,
   comienzo_martes int,
   finaliza_martes int,
   comienzo_miercoles int,
   finaliza_miercoles int,
   comienzo_jueves int,
   finaliza_jueves int,
   comienzo_viernes int,
   finaliza_viernes int,
   comienzo_sabado int,
   finaliza_sabado int,
   frecuencia int,
  PRIMARY KEY (`numero`),
  CONSTRAINT `horario_ibfk_1`
  FOREIGN KEY (`id_doctor`)
  REFERENCES `usuarios2`.`medico` (`idMedicos`));
  
  
  -- -----------------------------------------------------
-- Table `usuarios2`.`slot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios2`.`slot` (
  `idDoctor`  VARCHAR(45) NOT NULL,
   `id` INT auto_increment NOT NULL,
  `checked` boolean NULL,
  `desde`  VARCHAR(45) NULL,
  `hasta` VARCHAR(45) NULL,
  
  PRIMARY KEY (`id`),  
  CONSTRAINT `slot_ibfk_1`
  FOREIGN KEY (`idDoctor`)
  REFERENCES `usuarios2`.`medico` (`idMedicos`));
  
  insert into slot (idDoctor,checked, desde, hasta)values('2222',TRUE,'9:30','4:00');
  insert into slot (idDoctor,checked, desde, hasta)values('2222',TRUE,'7:00','3:30');
  insert into slot (idDoctor,checked, desde, hasta)values('2222',TRUE,'4:30','6:00');
  insert into slot (idDoctor,checked, desde, hasta)values('2222',TRUE,'8:00','3:00');
  insert into slot (idDoctor,checked, desde, hasta)values('2222',TRUE,'8:00','3:00');
  insert into slot (idDoctor,checked, desde, hasta)values('1111',TRUE,'6:30','2:30');
  insert into slot (idDoctor,checked, desde, hasta)values('1111',TRUE,'3:00','6:30');
  insert into slot (idDoctor,checked, desde, hasta)values('1111',TRUE,'9:00','2:00');
  insert into slot (idDoctor,checked, desde, hasta)values('1111',TRUE,'5:30','4:00');
  insert into slot (idDoctor,checked, desde, hasta)values('1111',TRUE,'3:00','6:30');
  
  
  insert into horario(id_doctor,comienzo_lunes,finaliza_lunes,comienzo_martes,finaliza_martes,
comienzo_miercoles,finaliza_miercoles,comienzo_jueves,finaliza_jueves,comienzo_viernes,finaliza_viernes,
comienzo_sabado, finaliza_sabado, frecuencia) values('1111','8','10','8','10','8','10','8','10','8','10','8','10','1');

  insert into horario(id_doctor,comienzo_lunes,finaliza_lunes,comienzo_martes,finaliza_martes,
comienzo_miercoles,finaliza_miercoles,comienzo_jueves,finaliza_jueves,comienzo_viernes,finaliza_viernes,
comienzo_sabado, finaliza_sabado, frecuencia) values('2222','8','10','8','10','8','10','8','10','8','10','8','10','1');

  insert into horario(id_doctor,comienzo_lunes,finaliza_lunes,comienzo_martes,finaliza_martes,
comienzo_miercoles,finaliza_miercoles,comienzo_jueves,finaliza_jueves,comienzo_viernes,finaliza_viernes,
comienzo_sabado, finaliza_sabado, frecuencia) values('3333','8','10','8','10','8','10','8','10','8','10','8','10','1');
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
